comentarios = [
    "La comida estuvo deliciosa, volveré seguro.",
    "El servicio fue muy lento, no estoy satisfecho.",
    "El ambiente es agradable, pero la comida es promedio.",
    "¡Me encantó la pasta! Fue la mejor que he probado.",
    "El personal fue grosero y no atendió bien.",
    "Es un lugar normal, no destaca en nada.",
    "La cena fue exquisita, especialmente el postre.",
    "El menú es muy limitado, esperaba más opciones.",
    "Un restaurante increíble, lo recomiendo a todos.",
    "La comida llegó fría y no era lo que pedí.",
    "El lugar es bonito, pero no volveré por la comida.",
    "Fue una experiencia neutral, ni buena ni mala.",
    "El sushi es fresco y sabroso, muy recomendable.",
    "No entiendo por qué hay tantas buenas críticas.",
    "El café es excelente, perfecto para terminar la comida.",
    "El precio es alto para lo que ofrecen.",
    "Disfruté mucho la cena, el servicio fue rápido.",
    "El lugar es ruidoso y no se puede conversar bien.",
    "Es un restaurante con buenas opciones vegetarianas.",
    "Me decepcionó que no tuvieran lo que pedí.",
    "La atención fue excepcional, me hicieron sentir especial.",
    "El diseño es bonito, pero no muy funcional.",
    "Un total fracaso. No lo compraré de nuevo.",
    "Estoy neutral al respecto, no tengo sentimientos fuertes.",
    "Estuvo bien rico",
    "Estuvo bien crudo",
    "La comida estuvo rica, pero la atención estuvo pesimo.",
    "La comida bien rica, atención de primera calidad"
]